coretasks: fix last_who AttributeError
On servers that don't support away-notify, the _periodic_who task would
cause `AttributeError: 'Identifier' object has no attribute 'last_who'`

Co-Authored-By: dgw <dgw@technobabbl.es>